In [1]:
from io import StringIO
import time
import os
import requests
import pandas as pd
import numpy as np

In [5]:
# URL of the page with the list of IPOS
url = "https://www.iposcoop.com/ipos-recently-filed/"

# Setting the header for the HTTP request
headers = {'User-Agent': 'Mozilla/5.0'}

In [6]:
# Making the HTTP request to get the page content
response = requests.get(url, headers=headers)

# Reading the tables from the HTML page using pandas
tables = pd.read_html(StringIO(response.text))

In [7]:
# Displaying the number of tables found
print(len(tables))   

# Displaying the first rows of the first table
tables[0].head()

1

,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating
0,2026-09-22,Accelevation Holdings Corp.,ACCV,Morgan Stanley/J.P. Morgan/Goldman Sachs/Barcl...,30.00,$20.00,$24.00,$660.00,Wednesday,S/O
1,2026-09-22,Live Oak Acquisition VI,LOVIU,Santander,20.00,$10.00,$10.00,$200.00,Priced,S/O
2,2026-09-21,ADARx Pharmaceuticals,ADRX,J.P.Morgan/Morgan Stanley/TD Cowen/UBS Investm...,21.88,$15.00,$17.00,$350.00,Friday,S/O
3,2026-09-21,Iambic Therapeutics,IAM,J.P.Morgan/Jefferies/BofA Securities/Citigroup,0.00,NaN,NaN,$100.00,TBA,S/O
4,2026-09-21,Oura,OURA,Goldman Sachs/Morgan Stanley/J.P.Morgan/Allen ...,50.00,$40.00,$44.00,$2100.00,Wednesday,S/O

In [10]:
tables

[      File Date                           Company  Symbol  \
 0    2026-09-22       Accelevation Holdings Corp.    ACCV
 1    2026-09-22           Live Oak Acquisition VI   LOVIU
 2    2026-09-21             ADARx Pharmaceuticals    ADRX
 3    2026-09-21               Iambic Therapeutics     IAM
 4    2026-09-21                              Oura    OURA
 ..          ...                               ...     ...
 495  2025-12-23                         AOJE Inc.    AOJE
 496  2025-12-23    Spartacus Acquisition Corp. II   TMTSU
 497  2025-12-22  Silicon Valley Acquisition Corp.   SVAQU
 498  2025-12-22          Social Commerce Partners   SCPQU
 499  2025-12-19            Legato Merger Corp. IV  LEGO.U

                                               Managers  Shares (millions)  \
 0    Morgan Stanley/J.P. Morgan/Goldman Sachs/Barcl...              30.00
 1                                            Santander              20.00
 2    J.P.Morgan/Morgan Stanley/TD Cowen/UBS Investm...              21.88
 3       J.P.Morgan/Jefferies/BofA Securities/Citigroup               0.00
 4    Goldman Sachs/Morgan Stanley/J.P.Morgan/Allen ...              50.00
 ..                                                 ...                ...
 495                                  Revere Securities               0.00
 496                                               BTIG              20.00
 497                                       Clear Street              20.00
 498                                               BTIG              10.00
 499                                               BTIG              20.00

     Price Low Price High Est $ Vol (millions) Expected To Trade SCOOP Rating
 0      $20.00     $24.00              $660.00         Wednesday          S/O
 1      $10.00     $10.00              $200.00            Priced          S/O
 2      $15.00     $17.00              $350.00            Friday          S/O
 3         NaN        NaN              $100.00               TBA          S/O
 4      $40.00     $44.00             $2100.00         Wednesday          S/O
 ..        ...        ...                  ...               ...          ...
 495       NaN        NaN               $30.00               TBA          S/O
 496    $10.00     $10.00              $200.00            Priced          S/O
 497    $10.00     $10.00              $200.00            Priced          S/O
 498    $10.00     $10.00              $100.00            Priced          S/O
 499    $10.00     $10.00              $200.00            Priced          S/O

 [500 rows x 10 columns]]

In [6]:
df = tables[0]

In [9]:
df.to_csv(r'../data/ipo.csv', index=False)

In [11]:
# Function to get the names of all tables in a given URL
def scrapping(urls, table):
    # URL of the page with the list of companies
    url = urls

    # Setting the header for the HTTP request
    headers = {'User-Agent': 'Mozilla/5.0'}
    
    # Making the HTTP request to get the page content
    response = requests.get(url, headers=headers)
    
    # Checking whether the table is present in the page content
    check_response = table in response.text
    
    # Reading the tables from the HTML page using pandas
    if check_response == True:
        print(f'Table {table} status: {check_response}')
        # Reading the tables from the HTML page using pandas
        tables = pd.read_html(StringIO(response.text), match=table)
        df = tables[0]  
    
    return df

In [15]:
# Function to get the names of the tables on an HTML page
def get_html_tables_name(urls):
    """
    Function to get the names of the tables on an HTML page.
    
    Parameters:
    - response: HTTP response object containing the page content.
    
    Returns:
    - List with the names of the tables found on the page.
    """
    
    # URL of the page with the list of companies
    url = urls

    # Setting the header for the HTTP request
    headers = {'User-Agent': 'Mozilla/5.0'}

    # Making the HTTP request to get the page content
    response = requests.get(url, headers=headers)
    
    # Reading the tables from the HTML page using pandas
    tables = pd.read_html(StringIO(response.text))
    print(len(tables))

    # Displaying the number of tables found and the first 5 columns of each table
    for i, t in enumerate(tables):
        print(i, t.shape, list(t.columns)[:5])

In [16]:
check_tables_names = get_html_tables_name('https://www.iposcoop.com/ipos-recently-filed/')

1
0 (500, 10) ['File Date', 'Company', 'Symbol', 'Managers', 'Shares (millions)']

In [14]:
check_tables = scrapping(0,'https://www.iposcoop.com/ipos-recently-filed/')

MissingSchema: Invalid URL '0': No scheme supplied. Perhaps you meant https://0?

---

### Question 1

In [2]:
df = pd.read_csv(r'../data/ipo.csv')

In [3]:
df

,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating
0,2026-09-22,Accelevation Holdings Corp.,ACCV,Morgan Stanley/J.P. Morgan/Goldman Sachs/Barcl...,30.00,$20.00,$24.00,$660.00,Wednesday,S/O
1,2026-09-21,ADARx Pharmaceuticals,ADRX,J.P.Morgan/Morgan Stanley/TD Cowen/UBS Investm...,21.88,$15.00,$17.00,$350.00,Friday,S/O
2,2026-09-21,Iambic Therapeutics,IAM,J.P.Morgan/Jefferies/BofA Securities/Citigroup,0.00,NaN,NaN,$100.00,TBA,S/O
3,2026-09-21,Oura,OURA,Goldman Sachs/Morgan Stanley/J.P.Morgan/Allen ...,50.00,$40.00,$44.00,$2100.00,Wednesday,S/O
4,2026-09-21,Silicon Valley Acquisition II,SVATU,Cohen & Company Capital Markets,22.00,$10.00,$10.00,$220.00,TBA,S/O
...,...,...,...,...,...,...,...,...,...,...
495,2025-12-23,Spartacus Acquisition Corp. II,TMTSU,BTIG,20.00,$10.00,$10.00,$200.00,Priced,S/O
496,2025-12-22,Silicon Valley Acquisition Corp.,SVAQU,Clear Street,20.00,$10.00,$10.00,$200.00,Priced,S/O
497,2025-12-22,Social Commerce Partners,SCPQU,BTIG,10.00,$10.00,$10.00,$100.00,Priced,S/O
498,2025-12-19,Legato Merger Corp. IV,LEGO.U,BTIG,20.00,$10.00,$10.00,$200.00,Priced,S/O
499,2025-12-19,Monkey Tree Investment Ltd.,MKTR,Craft Capital Management/Revere Securities,1.60,$4.00,$5.00,$7.00,TBA,S/O

In [97]:
df_witdrawn = df[df['Expected To Trade'] == 'Withdrawn']

In [98]:
df_witdrawn.reset_index(inplace=True)

In [99]:
df_witdrawn

,index,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating
0,8,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,$4.00,$5.00,$16.88,Withdrawn,S/O
1,21,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,$4.50,$5.50,$22.00,Withdrawn,S/O
2,27,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,$100.00,Withdrawn,S/O
3,33,2026-09-04,Idea Tech Holding (Withdrawn),IDTL,R.F. Lafferty & Co.,2.00,$4.00,$5.00,$9.00,Withdrawn,S/O
4,42,2026-09-01,Hornbeck Offshore Services (Withdrawn),HOS,J.P. Morgan/ Barclays/DNB Markets/Piper Sandle...,0.00,NaN,NaN,$100.00,Withdrawn,S/O
5,44,2026-08-31,Coolbit Technologies Ltd. (Withdrawn),CBAI,Eddid Securities USA,5.00,$4.00,$5.00,$22.50,Withdrawn,S/O
6,52,2026-08-27,Timber Road Acquisition Corp. (Withdrawn),TMRDU,Roth Capital Partners/Stone X Financial Inc.,20.00,$10.00,$10.00,$200.00,Withdrawn,S/O
7,63,2026-08-24,pan-Africa Corp. (Withdrawn),BLEUU,Santander,12.50,$10.00,$10.00,$125.00,Withdrawn,S/O
8,78,2026-08-18,Living Homeopathy (Withdrawn),LHI,Revere Securities,3.75,$4.00,$6.00,$19.00,Withdrawn,S/O
9,121,2026-07-31,Nuclea Energy (Withdrawn),NCLA,Joseph Gunnar & Co.,5.60,$8.00,$10.00,$50.40,Withdrawn,S/O
10,151,2026-07-10,APEX Global Solutions Ltd. (WITHDRAWN),APEX,US Tiger Securities,3.75,$4.00,$4.00,$15.00,Withdrawn,S/O
11,156,2026-07-08,Cloud Data Holdings (Withdrawn),CDN,Cathay Securities,3.75,$4.00,$4.50,$15.94,Withdrawn,S/O
12,158,2026-07-08,INFINT Acquisition Corp. 2 (Withdrawn),TBA,Roth Capital Partners,10.00,$10.00,$10.00,$100.00,Withdrawn,S/O
13,178,2026-06-24,Kilcoy Global Foods Ltd. (Withdrawn),KGF,Citigroup/Morgan Stanley,0.00,NaN,NaN,$100.00,Withdrawn,S/O
14,179,2026-06-24,Safepoint Holdings (Withdrawn),SFPT,Deutsche Bank Securities/Morgan Stanley/Keefe ...,16.67,$15.00,$17.00,$266.72,Withdrawn,S/O
15,189,2026-06-11,Club Versante Group Ltd.,CADV,Joseph Stone Capital,2.00,$4.00,$6.00,$10.00,Withdrawn,S/O
16,193,2026-06-10,Helio Corp. (NYSE-AmEx Uplisting – Unit Deal),HLEO,ThinkEquity,3.33,$4.00,$5.00,$15.00,Withdrawn,S/O
17,219,2026-06-01,Envoy Technologies (Withdrawn – Direct Listing),EVOY,Roth Capital Partners,7.80,$8.00,$8.00,$62.40,Withdrawn,S/O
18,237,2026-05-20,Vistek Limited (Withdrawn),VTEK,Bancroft Capital,6.25,$4.00,$6.00,$31.00,Withdrawn,S/O
19,253,2026-05-13,Ultratrex (Withdrawn),UTX,Craft Capital Management,1.25,$4.00,$6.00,$6.25,Withdrawn,S/O
20,261,2026-05-07,AiXin Life International,AIXN,Network 1 Financial Securities,2.38,$4.00,$4.00,$9.50,Withdrawn,S/O
21,267,2026-05-06,Xinxu Copper Industry Technology Ltd.,XXC,Craft Capital/ R.F. Lafferty & Co.,0.00,NaN,NaN,$15.00,Withdrawn,S/O
22,268,2026-05-05,EUPEC International Group Ltd.,EUPX,R.F. Lafferty & Co.,3.75,$4.00,$4.00,$15.00,Withdrawn,S/O
23,274,2026-05-01,CCIS Acquisition Corp.,CCACU,Benjamin Securities,6.00,$10.00,$10.00,$60.00,Withdrawn,S/O
24,328,2026-04-01,Going International Holding Company Limited,GIT,Prime Number Capital,0.00,NaN,NaN,$20.00,Withdrawn,S/O
25,350,2026-03-16,Firefly Automatix,FFLY,Roth Capital Markets/Lake Street Capital Markets,4.55,$4.50,$6.50,$25.00,Withdrawn,S/O
26,366,2026-03-06,Invea Therapeutics (Withdrawn),INAI,BofA Securities/ Citigroup/ Truist Securities,0.00,NaN,NaN,$75.00,Withdrawn,S/O
27,371,2026-02-27,Billion Group Holdings (Withdrawn),BGHL,American Trust Investment Services,1.50,$4.00,$6.00,$7.50,Withdrawn,S/O
28,382,2026-02-24,AIGO Holding Ltd.,AIGO,Eddid Securities USA,2.00,$4.00,$6.00,$10.00,Withdrawn,S/O
29,390,2026-02-19,Clear Street Group Inc. (Withdrawn),CLRS,Goldman Sachs/BofA Securities/Morgan Stanley/U...,13.00,$26.00,$28.00,$351.00,Withdrawn,S/O
30,404,2026-02-13,Lemeng Holdings (Withdrawn),LIAI,Prime Number Capital,4.00,$4.00,$6.00,$20.00,Withdrawn,S/O
31,457,2026-01-27,SFIDA X,SFDX,ThinkEquity,1.00,$5.00,$6.00,$5.50,Withdrawn,S/O
32,486,2026-01-06,"Altech Digital Co., Ltd.",ALD,Pacific Century Securities/Revere Securities,1.50,$4.00,$4.00,$6.00,Withdrawn,S/O

In [100]:
conditions = [
    df_witdrawn['Company'].str.contains('Technologies', case=False, na=False),
    df_witdrawn['Company'].str.contains('Acquisition Corp|Acquisition Corporation|\bCorp\b|Corp\.', case=False, na=False),
    df_witdrawn['Company'].str.contains('Inc|Incorporated', case=False, na=False),
    df_witdrawn['Company'].str.contains('Group', case=False, na=False),
    df_witdrawn['Company'].str.contains('Ltd|Limited', case=False, na=False),
    df_witdrawn['Company'].str.contains('Holdings|Holding', case=False, na=False)
]

<>:3: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
<>:3: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
C:\Users\leona\AppData\Local\Temp\ipykernel_4764\3844577696.py:3: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
  df_witdrawn['Company'].str.contains('Acquisition Corp|Acquisition Corporation|\bCorp\b|Corp\.', case=False, na=False),

In [101]:
choices = [
    'Technologies',
    'Acquisition Corp',
    'Inc.',
    'Group',
    'Limited',
    'Holdings'
]

In [102]:
df_witdrawn['Company Type'] = np.select(conditions, choices, default='Other')

In [103]:
df_witdrawn

,index,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating,Company Type
0,8,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,$4.00,$5.00,$16.88,Withdrawn,S/O,Group
1,21,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,$4.50,$5.50,$22.00,Withdrawn,S/O,Limited
2,27,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,$100.00,Withdrawn,S/O,Technologies
3,33,2026-09-04,Idea Tech Holding (Withdrawn),IDTL,R.F. Lafferty & Co.,2.00,$4.00,$5.00,$9.00,Withdrawn,S/O,Holdings
4,42,2026-09-01,Hornbeck Offshore Services (Withdrawn),HOS,J.P. Morgan/ Barclays/DNB Markets/Piper Sandle...,0.00,NaN,NaN,$100.00,Withdrawn,S/O,Other
5,44,2026-08-31,Coolbit Technologies Ltd. (Withdrawn),CBAI,Eddid Securities USA,5.00,$4.00,$5.00,$22.50,Withdrawn,S/O,Technologies
6,52,2026-08-27,Timber Road Acquisition Corp. (Withdrawn),TMRDU,Roth Capital Partners/Stone X Financial Inc.,20.00,$10.00,$10.00,$200.00,Withdrawn,S/O,Acquisition Corp
7,63,2026-08-24,pan-Africa Corp. (Withdrawn),BLEUU,Santander,12.50,$10.00,$10.00,$125.00,Withdrawn,S/O,Acquisition Corp
8,78,2026-08-18,Living Homeopathy (Withdrawn),LHI,Revere Securities,3.75,$4.00,$6.00,$19.00,Withdrawn,S/O,Other
9,121,2026-07-31,Nuclea Energy (Withdrawn),NCLA,Joseph Gunnar & Co.,5.60,$8.00,$10.00,$50.40,Withdrawn,S/O,Other
10,151,2026-07-10,APEX Global Solutions Ltd. (WITHDRAWN),APEX,US Tiger Securities,3.75,$4.00,$4.00,$15.00,Withdrawn,S/O,Limited
11,156,2026-07-08,Cloud Data Holdings (Withdrawn),CDN,Cathay Securities,3.75,$4.00,$4.50,$15.94,Withdrawn,S/O,Holdings
12,158,2026-07-08,INFINT Acquisition Corp. 2 (Withdrawn),TBA,Roth Capital Partners,10.00,$10.00,$10.00,$100.00,Withdrawn,S/O,Acquisition Corp
13,178,2026-06-24,Kilcoy Global Foods Ltd. (Withdrawn),KGF,Citigroup/Morgan Stanley,0.00,NaN,NaN,$100.00,Withdrawn,S/O,Limited
14,179,2026-06-24,Safepoint Holdings (Withdrawn),SFPT,Deutsche Bank Securities/Morgan Stanley/Keefe ...,16.67,$15.00,$17.00,$266.72,Withdrawn,S/O,Holdings
15,189,2026-06-11,Club Versante Group Ltd.,CADV,Joseph Stone Capital,2.00,$4.00,$6.00,$10.00,Withdrawn,S/O,Group
16,193,2026-06-10,Helio Corp. (NYSE-AmEx Uplisting – Unit Deal),HLEO,ThinkEquity,3.33,$4.00,$5.00,$15.00,Withdrawn,S/O,Acquisition Corp
17,219,2026-06-01,Envoy Technologies (Withdrawn – Direct Listing),EVOY,Roth Capital Partners,7.80,$8.00,$8.00,$62.40,Withdrawn,S/O,Technologies
18,237,2026-05-20,Vistek Limited (Withdrawn),VTEK,Bancroft Capital,6.25,$4.00,$6.00,$31.00,Withdrawn,S/O,Limited
19,253,2026-05-13,Ultratrex (Withdrawn),UTX,Craft Capital Management,1.25,$4.00,$6.00,$6.25,Withdrawn,S/O,Other
20,261,2026-05-07,AiXin Life International,AIXN,Network 1 Financial Securities,2.38,$4.00,$4.00,$9.50,Withdrawn,S/O,Other
21,267,2026-05-06,Xinxu Copper Industry Technology Ltd.,XXC,Craft Capital/ R.F. Lafferty & Co.,0.00,NaN,NaN,$15.00,Withdrawn,S/O,Limited
22,268,2026-05-05,EUPEC International Group Ltd.,EUPX,R.F. Lafferty & Co.,3.75,$4.00,$4.00,$15.00,Withdrawn,S/O,Group
23,274,2026-05-01,CCIS Acquisition Corp.,CCACU,Benjamin Securities,6.00,$10.00,$10.00,$60.00,Withdrawn,S/O,Acquisition Corp
24,328,2026-04-01,Going International Holding Company Limited,GIT,Prime Number Capital,0.00,NaN,NaN,$20.00,Withdrawn,S/O,Limited
25,350,2026-03-16,Firefly Automatix,FFLY,Roth Capital Markets/Lake Street Capital Markets,4.55,$4.50,$6.50,$25.00,Withdrawn,S/O,Other
26,366,2026-03-06,Invea Therapeutics (Withdrawn),INAI,BofA Securities/ Citigroup/ Truist Securities,0.00,NaN,NaN,$75.00,Withdrawn,S/O,Other
27,371,2026-02-27,Billion Group Holdings (Withdrawn),BGHL,American Trust Investment Services,1.50,$4.00,$6.00,$7.50,Withdrawn,S/O,Group
28,382,2026-02-24,AIGO Holding Ltd.,AIGO,Eddid Securities USA,2.00,$4.00,$6.00,$10.00,Withdrawn,S/O,Limited
29,390,2026-02-19,Clear Street Group Inc. (Withdrawn),CLRS,Goldman Sachs/BofA Securities/Morgan Stanley/U...,13.00,$26.00,$28.00,$351.00,Withdrawn,S/O,Inc.
30,404,2026-02-13,Lemeng Holdings (Withdrawn),LIAI,Prime Number Capital,4.00,$4.00,$6.00,$20.00,Withdrawn,S/O,Holdings
31,457,2026-01-27,SFIDA X,SFDX,ThinkEquity,1.00,$5.00,$6.00,$5.50,Withdrawn,S/O,Other
32,486,2026-01-06,"Altech Digital Co., Ltd.",ALD,Pacific Century Securities/Revere Securities,1.50,$4.00,$4.00,$6.00,Withdrawn,S/O,Limited

In [104]:
df_witdrawn.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 33 non-null     int64
 1   File Date             33 non-null     str
 2   Company               33 non-null     str
 3   Symbol                33 non-null     str
 4   Managers              33 non-null     str
 5   Shares (millions)     33 non-null     float64
 6   Price Low             27 non-null     str
 7   Price High            27 non-null     str
 8   Est $ Vol (millions)  33 non-null     str
 9   Expected To Trade     33 non-null     str
 10  SCOOP Rating          33 non-null     str
 11  Company Type          33 non-null     str
dtypes: float64(1), int64(1), str(10)
memory usage: 3.2 KB

In [109]:
for col in ['Price High', 'Price Low', 'Est $ Vol (millions)', 'Shares (millions)']:
    df_witdrawn[col] = (
        df_witdrawn[col]
        .astype(str)
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.strip()
    )
    df_witdrawn[col] = pd.to_numeric(df_witdrawn[col], errors='coerce')

In [110]:
df_witdrawn

,index,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating,Company Type,Avg Price
0,8,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,4.0,5.0,16.88,Withdrawn,S/O,Group,4.50
1,21,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,4.5,5.5,22.00,Withdrawn,S/O,Limited,5.00
2,27,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Technologies,NaN
3,33,2026-09-04,Idea Tech Holding (Withdrawn),IDTL,R.F. Lafferty & Co.,2.00,4.0,5.0,9.00,Withdrawn,S/O,Holdings,4.50
4,42,2026-09-01,Hornbeck Offshore Services (Withdrawn),HOS,J.P. Morgan/ Barclays/DNB Markets/Piper Sandle...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Other,NaN
5,44,2026-08-31,Coolbit Technologies Ltd. (Withdrawn),CBAI,Eddid Securities USA,5.00,4.0,5.0,22.50,Withdrawn,S/O,Technologies,4.50
6,52,2026-08-27,Timber Road Acquisition Corp. (Withdrawn),TMRDU,Roth Capital Partners/Stone X Financial Inc.,20.00,10.0,10.0,200.00,Withdrawn,S/O,Acquisition Corp,10.00
7,63,2026-08-24,pan-Africa Corp. (Withdrawn),BLEUU,Santander,12.50,10.0,10.0,125.00,Withdrawn,S/O,Acquisition Corp,10.00
8,78,2026-08-18,Living Homeopathy (Withdrawn),LHI,Revere Securities,3.75,4.0,6.0,19.00,Withdrawn,S/O,Other,5.00
9,121,2026-07-31,Nuclea Energy (Withdrawn),NCLA,Joseph Gunnar & Co.,5.60,8.0,10.0,50.40,Withdrawn,S/O,Other,9.00
10,151,2026-07-10,APEX Global Solutions Ltd. (WITHDRAWN),APEX,US Tiger Securities,3.75,4.0,4.0,15.00,Withdrawn,S/O,Limited,4.00
11,156,2026-07-08,Cloud Data Holdings (Withdrawn),CDN,Cathay Securities,3.75,4.0,4.5,15.94,Withdrawn,S/O,Holdings,4.25
12,158,2026-07-08,INFINT Acquisition Corp. 2 (Withdrawn),TBA,Roth Capital Partners,10.00,10.0,10.0,100.00,Withdrawn,S/O,Acquisition Corp,10.00
13,178,2026-06-24,Kilcoy Global Foods Ltd. (Withdrawn),KGF,Citigroup/Morgan Stanley,0.00,NaN,NaN,100.00,Withdrawn,S/O,Limited,NaN
14,179,2026-06-24,Safepoint Holdings (Withdrawn),SFPT,Deutsche Bank Securities/Morgan Stanley/Keefe ...,16.67,15.0,17.0,266.72,Withdrawn,S/O,Holdings,16.00
15,189,2026-06-11,Club Versante Group Ltd.,CADV,Joseph Stone Capital,2.00,4.0,6.0,10.00,Withdrawn,S/O,Group,5.00
16,193,2026-06-10,Helio Corp. (NYSE-AmEx Uplisting – Unit Deal),HLEO,ThinkEquity,3.33,4.0,5.0,15.00,Withdrawn,S/O,Acquisition Corp,4.50
17,219,2026-06-01,Envoy Technologies (Withdrawn – Direct Listing),EVOY,Roth Capital Partners,7.80,8.0,8.0,62.40,Withdrawn,S/O,Technologies,8.00
18,237,2026-05-20,Vistek Limited (Withdrawn),VTEK,Bancroft Capital,6.25,4.0,6.0,31.00,Withdrawn,S/O,Limited,5.00
19,253,2026-05-13,Ultratrex (Withdrawn),UTX,Craft Capital Management,1.25,4.0,6.0,6.25,Withdrawn,S/O,Other,5.00
20,261,2026-05-07,AiXin Life International,AIXN,Network 1 Financial Securities,2.38,4.0,4.0,9.50,Withdrawn,S/O,Other,4.00
21,267,2026-05-06,Xinxu Copper Industry Technology Ltd.,XXC,Craft Capital/ R.F. Lafferty & Co.,0.00,NaN,NaN,15.00,Withdrawn,S/O,Limited,NaN
22,268,2026-05-05,EUPEC International Group Ltd.,EUPX,R.F. Lafferty & Co.,3.75,4.0,4.0,15.00,Withdrawn,S/O,Group,4.00
23,274,2026-05-01,CCIS Acquisition Corp.,CCACU,Benjamin Securities,6.00,10.0,10.0,60.00,Withdrawn,S/O,Acquisition Corp,10.00
24,328,2026-04-01,Going International Holding Company Limited,GIT,Prime Number Capital,0.00,NaN,NaN,20.00,Withdrawn,S/O,Limited,NaN
25,350,2026-03-16,Firefly Automatix,FFLY,Roth Capital Markets/Lake Street Capital Markets,4.55,4.5,6.5,25.00,Withdrawn,S/O,Other,5.50
26,366,2026-03-06,Invea Therapeutics (Withdrawn),INAI,BofA Securities/ Citigroup/ Truist Securities,0.00,NaN,NaN,75.00,Withdrawn,S/O,Other,NaN
27,371,2026-02-27,Billion Group Holdings (Withdrawn),BGHL,American Trust Investment Services,1.50,4.0,6.0,7.50,Withdrawn,S/O,Group,5.00
28,382,2026-02-24,AIGO Holding Ltd.,AIGO,Eddid Securities USA,2.00,4.0,6.0,10.00,Withdrawn,S/O,Limited,5.00
29,390,2026-02-19,Clear Street Group Inc. (Withdrawn),CLRS,Goldman Sachs/BofA Securities/Morgan Stanley/U...,13.00,26.0,28.0,351.00,Withdrawn,S/O,Inc.,27.00
30,404,2026-02-13,Lemeng Holdings (Withdrawn),LIAI,Prime Number Capital,4.00,4.0,6.0,20.00,Withdrawn,S/O,Holdings,5.00
31,457,2026-01-27,SFIDA X,SFDX,ThinkEquity,1.00,5.0,6.0,5.50,Withdrawn,S/O,Other,5.50
32,486,2026-01-06,"Altech Digital Co., Ltd.",ALD,Pacific Century Securities/Revere Securities,1.50,4.0,4.0,6.00,Withdrawn,S/O,Limited,4.00

In [111]:
df_witdrawn['Avg Price'] = (df_witdrawn['Price High'] + df_witdrawn['Price Low']) / 2

In [112]:
df_witdrawn

,index,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating,Company Type,Avg Price
0,8,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,4.0,5.0,16.88,Withdrawn,S/O,Group,4.50
1,21,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,4.5,5.5,22.00,Withdrawn,S/O,Limited,5.00
2,27,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Technologies,NaN
3,33,2026-09-04,Idea Tech Holding (Withdrawn),IDTL,R.F. Lafferty & Co.,2.00,4.0,5.0,9.00,Withdrawn,S/O,Holdings,4.50
4,42,2026-09-01,Hornbeck Offshore Services (Withdrawn),HOS,J.P. Morgan/ Barclays/DNB Markets/Piper Sandle...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Other,NaN
5,44,2026-08-31,Coolbit Technologies Ltd. (Withdrawn),CBAI,Eddid Securities USA,5.00,4.0,5.0,22.50,Withdrawn,S/O,Technologies,4.50
6,52,2026-08-27,Timber Road Acquisition Corp. (Withdrawn),TMRDU,Roth Capital Partners/Stone X Financial Inc.,20.00,10.0,10.0,200.00,Withdrawn,S/O,Acquisition Corp,10.00
7,63,2026-08-24,pan-Africa Corp. (Withdrawn),BLEUU,Santander,12.50,10.0,10.0,125.00,Withdrawn,S/O,Acquisition Corp,10.00
8,78,2026-08-18,Living Homeopathy (Withdrawn),LHI,Revere Securities,3.75,4.0,6.0,19.00,Withdrawn,S/O,Other,5.00
9,121,2026-07-31,Nuclea Energy (Withdrawn),NCLA,Joseph Gunnar & Co.,5.60,8.0,10.0,50.40,Withdrawn,S/O,Other,9.00
10,151,2026-07-10,APEX Global Solutions Ltd. (WITHDRAWN),APEX,US Tiger Securities,3.75,4.0,4.0,15.00,Withdrawn,S/O,Limited,4.00
11,156,2026-07-08,Cloud Data Holdings (Withdrawn),CDN,Cathay Securities,3.75,4.0,4.5,15.94,Withdrawn,S/O,Holdings,4.25
12,158,2026-07-08,INFINT Acquisition Corp. 2 (Withdrawn),TBA,Roth Capital Partners,10.00,10.0,10.0,100.00,Withdrawn,S/O,Acquisition Corp,10.00
13,178,2026-06-24,Kilcoy Global Foods Ltd. (Withdrawn),KGF,Citigroup/Morgan Stanley,0.00,NaN,NaN,100.00,Withdrawn,S/O,Limited,NaN
14,179,2026-06-24,Safepoint Holdings (Withdrawn),SFPT,Deutsche Bank Securities/Morgan Stanley/Keefe ...,16.67,15.0,17.0,266.72,Withdrawn,S/O,Holdings,16.00
15,189,2026-06-11,Club Versante Group Ltd.,CADV,Joseph Stone Capital,2.00,4.0,6.0,10.00,Withdrawn,S/O,Group,5.00
16,193,2026-06-10,Helio Corp. (NYSE-AmEx Uplisting – Unit Deal),HLEO,ThinkEquity,3.33,4.0,5.0,15.00,Withdrawn,S/O,Acquisition Corp,4.50
17,219,2026-06-01,Envoy Technologies (Withdrawn – Direct Listing),EVOY,Roth Capital Partners,7.80,8.0,8.0,62.40,Withdrawn,S/O,Technologies,8.00
18,237,2026-05-20,Vistek Limited (Withdrawn),VTEK,Bancroft Capital,6.25,4.0,6.0,31.00,Withdrawn,S/O,Limited,5.00
19,253,2026-05-13,Ultratrex (Withdrawn),UTX,Craft Capital Management,1.25,4.0,6.0,6.25,Withdrawn,S/O,Other,5.00
20,261,2026-05-07,AiXin Life International,AIXN,Network 1 Financial Securities,2.38,4.0,4.0,9.50,Withdrawn,S/O,Other,4.00
21,267,2026-05-06,Xinxu Copper Industry Technology Ltd.,XXC,Craft Capital/ R.F. Lafferty & Co.,0.00,NaN,NaN,15.00,Withdrawn,S/O,Limited,NaN
22,268,2026-05-05,EUPEC International Group Ltd.,EUPX,R.F. Lafferty & Co.,3.75,4.0,4.0,15.00,Withdrawn,S/O,Group,4.00
23,274,2026-05-01,CCIS Acquisition Corp.,CCACU,Benjamin Securities,6.00,10.0,10.0,60.00,Withdrawn,S/O,Acquisition Corp,10.00
24,328,2026-04-01,Going International Holding Company Limited,GIT,Prime Number Capital,0.00,NaN,NaN,20.00,Withdrawn,S/O,Limited,NaN
25,350,2026-03-16,Firefly Automatix,FFLY,Roth Capital Markets/Lake Street Capital Markets,4.55,4.5,6.5,25.00,Withdrawn,S/O,Other,5.50
26,366,2026-03-06,Invea Therapeutics (Withdrawn),INAI,BofA Securities/ Citigroup/ Truist Securities,0.00,NaN,NaN,75.00,Withdrawn,S/O,Other,NaN
27,371,2026-02-27,Billion Group Holdings (Withdrawn),BGHL,American Trust Investment Services,1.50,4.0,6.0,7.50,Withdrawn,S/O,Group,5.00
28,382,2026-02-24,AIGO Holding Ltd.,AIGO,Eddid Securities USA,2.00,4.0,6.0,10.00,Withdrawn,S/O,Limited,5.00
29,390,2026-02-19,Clear Street Group Inc. (Withdrawn),CLRS,Goldman Sachs/BofA Securities/Morgan Stanley/U...,13.00,26.0,28.0,351.00,Withdrawn,S/O,Inc.,27.00
30,404,2026-02-13,Lemeng Holdings (Withdrawn),LIAI,Prime Number Capital,4.00,4.0,6.0,20.00,Withdrawn,S/O,Holdings,5.00
31,457,2026-01-27,SFIDA X,SFDX,ThinkEquity,1.00,5.0,6.0,5.50,Withdrawn,S/O,Other,5.50
32,486,2026-01-06,"Altech Digital Co., Ltd.",ALD,Pacific Century Securities/Revere Securities,1.50,4.0,4.0,6.00,Withdrawn,S/O,Limited,4.00

In [113]:
calculated_value = df_witdrawn['Shares (millions)'] * df_witdrawn['Avg Price']

In [114]:
df_witdrawn['Shares_offered_value'] = np.where(
    calculated_value.notna(),
    calculated_value,
    df_witdrawn['Est $ Vol (millions)']
)

In [115]:
df_witdrawn

,index,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating,Company Type,Avg Price,Shares_offered_value
0,8,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,4.0,5.0,16.88,Withdrawn,S/O,Group,4.50,16.8750
1,21,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,4.5,5.5,22.00,Withdrawn,S/O,Limited,5.00,22.0000
2,27,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Technologies,NaN,100.0000
3,33,2026-09-04,Idea Tech Holding (Withdrawn),IDTL,R.F. Lafferty & Co.,2.00,4.0,5.0,9.00,Withdrawn,S/O,Holdings,4.50,9.0000
4,42,2026-09-01,Hornbeck Offshore Services (Withdrawn),HOS,J.P. Morgan/ Barclays/DNB Markets/Piper Sandle...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Other,NaN,100.0000
5,44,2026-08-31,Coolbit Technologies Ltd. (Withdrawn),CBAI,Eddid Securities USA,5.00,4.0,5.0,22.50,Withdrawn,S/O,Technologies,4.50,22.5000
6,52,2026-08-27,Timber Road Acquisition Corp. (Withdrawn),TMRDU,Roth Capital Partners/Stone X Financial Inc.,20.00,10.0,10.0,200.00,Withdrawn,S/O,Acquisition Corp,10.00,200.0000
7,63,2026-08-24,pan-Africa Corp. (Withdrawn),BLEUU,Santander,12.50,10.0,10.0,125.00,Withdrawn,S/O,Acquisition Corp,10.00,125.0000
8,78,2026-08-18,Living Homeopathy (Withdrawn),LHI,Revere Securities,3.75,4.0,6.0,19.00,Withdrawn,S/O,Other,5.00,18.7500
9,121,2026-07-31,Nuclea Energy (Withdrawn),NCLA,Joseph Gunnar & Co.,5.60,8.0,10.0,50.40,Withdrawn,S/O,Other,9.00,50.4000
10,151,2026-07-10,APEX Global Solutions Ltd. (WITHDRAWN),APEX,US Tiger Securities,3.75,4.0,4.0,15.00,Withdrawn,S/O,Limited,4.00,15.0000
11,156,2026-07-08,Cloud Data Holdings (Withdrawn),CDN,Cathay Securities,3.75,4.0,4.5,15.94,Withdrawn,S/O,Holdings,4.25,15.9375
12,158,2026-07-08,INFINT Acquisition Corp. 2 (Withdrawn),TBA,Roth Capital Partners,10.00,10.0,10.0,100.00,Withdrawn,S/O,Acquisition Corp,10.00,100.0000
13,178,2026-06-24,Kilcoy Global Foods Ltd. (Withdrawn),KGF,Citigroup/Morgan Stanley,0.00,NaN,NaN,100.00,Withdrawn,S/O,Limited,NaN,100.0000
14,179,2026-06-24,Safepoint Holdings (Withdrawn),SFPT,Deutsche Bank Securities/Morgan Stanley/Keefe ...,16.67,15.0,17.0,266.72,Withdrawn,S/O,Holdings,16.00,266.7200
15,189,2026-06-11,Club Versante Group Ltd.,CADV,Joseph Stone Capital,2.00,4.0,6.0,10.00,Withdrawn,S/O,Group,5.00,10.0000
16,193,2026-06-10,Helio Corp. (NYSE-AmEx Uplisting – Unit Deal),HLEO,ThinkEquity,3.33,4.0,5.0,15.00,Withdrawn,S/O,Acquisition Corp,4.50,14.9850
17,219,2026-06-01,Envoy Technologies (Withdrawn – Direct Listing),EVOY,Roth Capital Partners,7.80,8.0,8.0,62.40,Withdrawn,S/O,Technologies,8.00,62.4000
18,237,2026-05-20,Vistek Limited (Withdrawn),VTEK,Bancroft Capital,6.25,4.0,6.0,31.00,Withdrawn,S/O,Limited,5.00,31.2500
19,253,2026-05-13,Ultratrex (Withdrawn),UTX,Craft Capital Management,1.25,4.0,6.0,6.25,Withdrawn,S/O,Other,5.00,6.2500
20,261,2026-05-07,AiXin Life International,AIXN,Network 1 Financial Securities,2.38,4.0,4.0,9.50,Withdrawn,S/O,Other,4.00,9.5200
21,267,2026-05-06,Xinxu Copper Industry Technology Ltd.,XXC,Craft Capital/ R.F. Lafferty & Co.,0.00,NaN,NaN,15.00,Withdrawn,S/O,Limited,NaN,15.0000
22,268,2026-05-05,EUPEC International Group Ltd.,EUPX,R.F. Lafferty & Co.,3.75,4.0,4.0,15.00,Withdrawn,S/O,Group,4.00,15.0000
23,274,2026-05-01,CCIS Acquisition Corp.,CCACU,Benjamin Securities,6.00,10.0,10.0,60.00,Withdrawn,S/O,Acquisition Corp,10.00,60.0000
24,328,2026-04-01,Going International Holding Company Limited,GIT,Prime Number Capital,0.00,NaN,NaN,20.00,Withdrawn,S/O,Limited,NaN,20.0000
25,350,2026-03-16,Firefly Automatix,FFLY,Roth Capital Markets/Lake Street Capital Markets,4.55,4.5,6.5,25.00,Withdrawn,S/O,Other,5.50,25.0250
26,366,2026-03-06,Invea Therapeutics (Withdrawn),INAI,BofA Securities/ Citigroup/ Truist Securities,0.00,NaN,NaN,75.00,Withdrawn,S/O,Other,NaN,75.0000
27,371,2026-02-27,Billion Group Holdings (Withdrawn),BGHL,American Trust Investment Services,1.50,4.0,6.0,7.50,Withdrawn,S/O,Group,5.00,7.5000
28,382,2026-02-24,AIGO Holding Ltd.,AIGO,Eddid Securities USA,2.00,4.0,6.0,10.00,Withdrawn,S/O,Limited,5.00,10.0000
29,390,2026-02-19,Clear Street Group Inc. (Withdrawn),CLRS,Goldman Sachs/BofA Securities/Morgan Stanley/U...,13.00,26.0,28.0,351.00,Withdrawn,S/O,Inc.,27.00,351.0000
30,404,2026-02-13,Lemeng Holdings (Withdrawn),LIAI,Prime Number Capital,4.00,4.0,6.0,20.00,Withdrawn,S/O,Holdings,5.00,20.0000
31,457,2026-01-27,SFIDA X,SFDX,ThinkEquity,1.00,5.0,6.0,5.50,Withdrawn,S/O,Other,5.50,5.5000
32,486,2026-01-06,"Altech Digital Co., Ltd.",ALD,Pacific Century Securities/Revere Securities,1.50,4.0,4.0,6.00,Withdrawn,S/O,Limited,4.00,6.0000

In [116]:
df_grouped = (
    df_witdrawn
    .groupby('Company Type')['Shares_offered_value']
    .sum()
    .reset_index()
)

In [117]:
df_grouped = df_grouped.sort_values(by='Shares_offered_value', ascending=False)

In [118]:
df_grouped

       Company Type  Shares_offered_value
0  Acquisition Corp              499.9850
3              Inc.              351.0000
2          Holdings              311.6575
5             Other              290.4450
4           Limited              219.2500
6      Technologies              184.9000
1             Group               49.3750

---

### Question 2